name: Clone and Push Repository
env:
  MAIN_REPO: https://${{secrets.USER_NAME}}:${{secrets.ACCESS_TOKEN}}@github.com/Shivamraghu1208/git-traning.git
  MAIN_BRANCH: master
on:
  [push]

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: java-training-new
        
      - name: Clone Repository
      
        run: |
          #git clone -b master https://${{secrets.USER_NAME}}:${{secrets.ACCESS_TOKEN}}@github.com/Shivamraghu1208/java-training-new.git master
          ls
          #cat master/src/com/training/First.java
          
          # cd ..
          git clone -b master  https://${{secrets.USER_NAME}}:${{secrets.ACCESS_TOKEN}}@github.com/Shivamraghu1208/testing.git master 
          echo "Hello"

          ls
            cp -r java-training-new master
           
           
           git status
          # git add master/src/com/training/First.java
          # git status
          # git diff
          
            
       
