name: Clone and Push Repository

on:
  [push]

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Clone Repository
      
        run: |
          git clone -b main https://${{secrets.USER_NAME}}:${{secrets.ACCESS_TOKEN}}@github.com/Shivamraghu1208/java-training-new.git master
          ls
          cat master/README.md
       
