name: Clone and Push Repository
env:
  MAIN_REPO: https://${{secrets.USER_NAME}}:${{secrets.ACCESS_TOKEN}}@github.com/Shivamraghu1208/testing.git
  MAIN_BRANCH: master
on:
  [push]

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: java-training-new

      - name: Clone Repository

        run: |
          ls
          git clone -b ${MAIN_BRANCH} ${MAIN_REPO} ${MAIN_BRANCH}


          ls master
          rm -rf java-training-new/.git
          rm -rf java-training-new/.github
          rm -rf master/java-training-new
          mv java-training-new master
          echo "after copy paste file"
          ls master
          cd master
          echo "before git status"
          git status
          echo "after git status"
          git diff
          git add java-training-new
          echo "after adding java-training-new"
          git config --global user.email "shivam.raghuwanshi@aurx.co"
          git config --global user.name "shivam"
          echo "after adding config name"
          git commit -m "adding file javatrainingnew"
          echo "after commit"
          git push origin master
          git status
          echo "after last line"

          
            
       
