name: Print README of Another Repository
env:
  MAIN_REPO: https://${{secrets.USER_NAME}}:${{secrets.ACCESS_TOKEN}}@github.com/Shivamraghu1208/git-traning.git
  MAIN_BRANCH: main
on:
  push:

jobs:
  print_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch README content
        run: |
          git clone -b ${MAIN_BRANCH} ${MAIN_REPO} ${MAIN_BRANCH}
          ls
          cat main/README.md

